package com.googlecode.tapestry5cayenne.model.auto;

import java.math.BigDecimal;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.googlecode.tapestry5cayenne.model.AcceptedBid;
import com.googlecode.tapestry5cayenne.model.Artist;
import com.googlecode.tapestry5cayenne.model.Painting;

/**
 * Class _Bid was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Bid extends CayenneDataObject {

    public static final String AMOUNT_PROPERTY = "amount";
    public static final String ACCEPTING_ARTISTS_PROPERTY = "acceptingArtists";
    public static final String BIDDER_PROPERTY = "bidder";
    public static final String PAINTING_PROPERTY = "painting";

    public static final String BIDID_PK_COLUMN = "bidid";

    public void setAmount(BigDecimal amount) {
        writeProperty("amount", amount);
    }
    public BigDecimal getAmount() {
        return (BigDecimal)readProperty("amount");
    }

    public void addToAcceptingArtists(AcceptedBid obj) {
        addToManyTarget("acceptingArtists", obj, true);
    }
    public void removeFromAcceptingArtists(AcceptedBid obj) {
        removeToManyTarget("acceptingArtists", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<AcceptedBid> getAcceptingArtists() {
        return (List<AcceptedBid>)readProperty("acceptingArtists");
    }


    public void setBidder(Artist bidder) {
        setToOneTarget("bidder", bidder, true);
    }

    public Artist getBidder() {
        return (Artist)readProperty("bidder");
    }


    public void setPainting(Painting painting) {
        setToOneTarget("painting", painting, true);
    }

    public Painting getPainting() {
        return (Painting)readProperty("painting");
    }


}
